server:
  port: 9091


spring:
  application:
    name: Goods
#    配置 mybatis
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/taobao?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    username: joker
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource


mybatis:
  mapper-locations: classpath:mapper/*.xml

  #将日志文件生成到系统盘路径
  type-aliases-package: com.ak

eureka:
  client:
    service-url:
      defaultZone: http://localhost:1000/eureka  #eureka注册地址
  instance:
    prefer-ip-address: true #是否显示服务器的ip地址
    instance-id: Goods9091 #客户端实例名称
