server:
  port: 8081
spring:
  application:
    name: provider_person_8081
#    配置 mybatis
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/taobao?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    username: joker
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
  resources:
    static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/,classpath:/upload/
# 开放静态资源
  mvc:
    static-path-pattern: classpath:/upload/,classpath:/resources/

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: common.pojo

eureka:
  client:
    service-url:
      defaultZone: http://localhost:80/eureka  #eureka注册地址
  instance:
    prefer-ip-address: true #是否显示服务器的ip地址
    instance-id: provider-8001 #客户端实例名称
