server:
  port: 81


eureka:
  client:
    service-url:
      defaultZone: http://localhost:1000/eureka  #eureka注册地址
  instance:
    prefer-ip-address: true #是否显示服务器的ip地址
    instance-id: consumer80 #客户端实例名称

spring:
  application:
    name: consumer80
#  main:
logging:
  level:
    com.ak.consumer.feign.GoodService: debug

ribbon:
  ReadTimeout: 5000
  ConnectTimeout: 5000

feign:
  hystrix:
    enabled: true
